# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

# Challenge 1

This is a placeholder to make the AI corrector be able to find the correct exercise for feedback

In [10]:
# Run this code:
salaries = pd.read_csv('../data/Current_Employee_Names__Salaries__and_Position_Titles.csv')

# import numpy and pandas
import pandas as pd
import numpy as np
from scipy.stats import trim_mean, mode, skew, gaussian_kde, pearsonr, spearmanr, beta
from statsmodels.stats.weightstats import ztest as ztest

from scipy.stats import ttest_ind, norm, t
from scipy.stats import f_oneway
from scipy.stats import sem

salaries = pd.read_csv('../data/Current_Employee_Names__Salaries__and_Position_Titles.csv')

display (salaries.head())
display (salaries.info())
display(salaries.describe())

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,101442.0,NaN
1,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
2,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,NaN,101592.0,NaN
3,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,110064.0,NaN
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 33183 entries, 0 to 33182
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Name               33183 non-null  object
 1   Job Titles         33183 non-null  object
 2   Department         33183 non-null  object
 3   Full or Part-Time  33183 non-null  object
 4   Salary or Hourly   33183 non-null  object
 5   Typical Hours      8022 non-null   float64
 6   Annual Salary      25161 non-null  float64
 7   Hourly Rate        8022 non-null   float64
dtypes: float64(3), object(5)
memory usage: 2.0+ MB

None

       Typical Hours  Annual Salary  Hourly Rate
count    8022.000000   25161.000000  8022.000000
mean       34.507604   86786.999790    32.788558
std         9.252077   21041.354602    12.112573
min        10.000000    7200.000000     2.650000
25%        20.000000   76266.000000    21.200000
50%        40.000000   90024.000000    35.600000
75%        40.000000   96060.000000    40.200000
max        40.000000  300000.000000   109.000000

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [25]:
# Your code here
# we this funtion to compare the average of one sample agains One value (30)

from scipy.stats import ttest_1samp

# 2. Filter to get the only hourly workers.. so we are gonne focus to the 'Hourly'..
# the colum of 'Salary or Horly' and take the row of  == 'horly'

# 3. Check the exact names of your columns first
print(hourly_workers.columns)

hourly_workers = salaries[salaries['Salary or Hourly']== 'Hourly' ].copy()

# Clean the data, if columns has gaps (NaN), WITH .'dropna()' removes them.

Hourly_rate = hourly_workers['Hourly Rate'].dropna()

#Perfom the hipotesis, just our excercise requested , compare our wages agains 30, use t_stat (herramienta)

t_stat, p_value = ttest_1samp(Hourly_rate, 30)

print(f"p-value: {p_value}")

#next sept, take the decision of (95% confidence = 0.05 error)
# if p_value < 0.05, the wage is significantly different from 30

if p_value  < 0.05:
    print(f" conlcusion: Reject H0(significant difference)")

else:
    print(f"conclusion: fail to reject H0 ( No significant diffence)")

Index(['Name', 'Job Titles', 'Department', 'Full or Part-Time',
       'Salary or Hourly', 'Typical Hours', 'Annual Salary', 'Hourly Rate'],
      dtype='object')
p-value: 4.3230240486229894e-92
 conlcusion: Reject H0(significant difference)

# Challenge 3

This is a placeholder to make the AI corrector be able to find the correct exercise for feedback

# Challenge 4 -  Hypothesis Tests of Proportions

## This challenge is OPTIONAL

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](https://www.statology.org/one-proportion-z-test/).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [32]:
# Your code here
# the goal: determinate if the propotion os horly workers is significantly  different from 0,25 (25%)
# the data :  we need first the number of "Horly" workers workers and the total number of rows. 
# import the proportions tool
from statsmodels.stats.proportion import proportions_ztest

# Count the cases, how many workers are working hourly? using--> shape[0] to count total worker hourly
total_workers_hourly = salaries[salaries['Salary or Hourly'] == 'Hourly']. shape [0]

# Workers in total, how many? (Total Sample) ( Muestra Total)

nobs = salaries.shape[0] # estamos contando aqui todos los salariados y en  total_workers_hourly filtramos los trabajadores por hora

# 25% value that we had to test 25% = 0,25

value = 0.25

# STARTT THE TEST
# z_stat es el puntaje de la distancia , p_value es nuestra probabilidad: imagina que el z_stat es un puntuaje de raraza, qué tan raro o nomal es un dato

z_stat,p_value = proportions_ztest(total_workers_hourly,nobs,value)

# Results
print (f"P-value : {p_value}")


if p_value < 0.05:
    print("Conclusion : reject H0, the value is significantly difrent from 25%")

else: 
    print("conclusion: Fail to reject H0")

P-value : 0.00044811272490579676
Conclusion : reject H0, the value is significantly difrent from 25%

In [ ]:
#The probability that the percentage is 25% is so small (e-92) that you reject the idea that it is 25%